spring.application.name=chat-app-backend
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb://localhost:27017/chatapp}
spring.data.mongodb.auto-index-creation=true
spring.ai.openai.api-key=${GROQ_API_KEY:<GROQ_API_KEY>}
spring.ai.openai.base-url=${SPRING_AI_OPENAI_BASE_URL:https://api.groq.com/openai}
spring.ai.openai.chat.options.model=${SPRING_AI_OPENAI_MODEL:llama-3.3-70b-versatile}
server.port=${PORT:8080}